spring:
  http:
    port: 8080
  server:
    ssl:
      enabled: false
  kafka:
    consumer:
      bootstrap-servers: localhost:8080
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    publisher:
      bootstrap-servers: localhost:9098
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:mysql://localhost:3306/learning
    username: root
    password: gime@job1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
url:
  server: http://localhost:9098/
  single: publisher/get/data1/
  multiple: publisher/get/data2?
  update-name-by-save: publisher/put/save?
  update-name-by-query: publisher/put/query?
